services:

  mysql:
    container_name: mysql
    image: "mysql:8.0.31"
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airflow
      MYSQL_USER: airflow
      MYSQL_PASSWORD: airflow
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u airflow --password=airflow
      interval: 30s  # Intervalo entre chequeos
      timeout: 240s   # Tiempo de espera antes de considerar fallido el chequeo
      retries: 10     # Número de intentos antes de marcar como unhealthy
    ports:
      - '3306:3306'
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - airflow_network

  airflow-webserver:
    image: apache/airflow:2.7.0-python3.11
    container_name: airflow-webserver
    restart: always
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql+mysqlconnector://airflow:airflow@mysql:3306/airflow
      - AIRFLOW_CONN_AIRFLOW_DB=mysql+mysqlconnector://airflow:airflow@mysql:3306/airflow
      - SQLALCHEMY_SILENCE_UBER_WARNING=1
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=aj38dk$#2LfK90mQwerTY*7zZxL4Vbn6!
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
    depends_on:
      - airflow-init
    command: >
      bash -c "airflow db upgrade && airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin && airflow webserver"
    networks:
      - airflow_network

  airflow-scheduler:
    image: apache/airflow:2.7.0-python3.11
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - airflow-webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql+mysqlconnector://airflow:airflow@mysql:3306/airflow
      - AIRFLOW_CONN_AIRFLOW_DB=mysql+mysqlconnector://airflow:airflow@mysql:3306/airflow
      - SQLALCHEMY_SILENCE_UBER_WARNING=1
      - AIRFLOW__WEBSERVER__SECRET_KEY=aj38dk$#2LfK90mQwerTY*7zZxL4Vbn6!
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
    command: airflow scheduler
    networks:
      - airflow_network

  airflow-triggerer:
    image: apache/airflow:2.7.0-python3.11
    command: triggerer
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql+mysqlconnector://airflow:airflow@mysql:3306/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=aj38dk$#2LfK90mQwerTY*7zZxL4Vbn6!
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
    depends_on:
      mysql:
        condition: service_healthy
        restart: "no"
    networks:
      - airflow_network

  airflow-init:
    image: apache/airflow:2.7.0-python3.11
    container_name: airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql+mysqlconnector://airflow:airflow@mysql:3306/airflow
      - AIRFLOW_CONN_AIRFLOW_DB=mysql+mysqlconnector://airflow:airflow@mysql:3306/airflow
      - SQLALCHEMY_SILENCE_UBER_WARNING=1
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=aj38dk$#2LfK90mQwerTY*7zZxL4Vbn6!
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
    entrypoint: >
      bash -c "sleep 30; airflow db init"
    restart: "no"
    networks:
      - airflow_network
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data:

networks:
  airflow_network:
    driver: bridge